name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test: 
    name: jobnaam

    runs-on: windows-2016

    steps:

    - name: configure
      run: C:\Users\stijn\Documents\GitHub\TestStijnGithub\testetstt

